### ISSUE TITLE
Add cookie container

### ISSUE THREAD

**Issue by abinop** [adamhartford/SwiftR#1]
How can I set cookies in the connection?

**Comment by adamhartford** [comment]
I need to add support for setting HTTP headers on the connection. That's next on the to-do list.

**Comment by abinop** [comment]
thank you @adamhartford

**Comment by adamhartford** [comment]
As of v0.4.0, cookies set in your app's NSHTTPCookieStorage will be sent to SignalR.

Manually setting a cookie:

```swift
let cookieProperties = [
    NSHTTPCookieName: "Foo",
    NSHTTPCookieValue: "Bar",
    NSHTTPCookieDomain: "myserver.com",
    NSHTTPCookiePath: "/",
]
let cookie = NSHTTPCookie(properties: cookieProperties)
NSHTTPCookieStorage.sharedHTTPCookieStorage().setCookie(cookie!)
```
