### ISSUE TITLE
Update to Swift 2.0

### ISSUE THREAD

**Issue by PranKe01** [adamhartford/SwiftR#10]
Please update to Swift 2.0, so no errors occur with XCode 7.

**Comment by adamhartford** [comment]
The master branch should already be Swift 2. There is a swift12 branch for Swift 1.2. What error are you getting?

**Comment by PranKe01** [comment]
I had to change the following lines:
                let fileManager = NSFileManager.defaultManager()
                try! fileManager.removeItemAtURL(jqueryTempURL)
                try! fileManager.removeItemAtURL(signalRTempURL)
                try! fileManager.removeItemAtURL(jsTempURL)
                try! fileManager.copyItemAtURL(jqueryURL, toURL: jqueryTempURL)
                try! fileManager.copyItemAtURL(signalRURL, toURL: signalRTempURL)
                try! fileManager.copyItemAtURL(jsURL, toURL: jsTempURL)
To this:
                let fileManager = NSFileManager.defaultManager()
                
                do {
                    try fileManager.removeItemAtURL(jqueryTempURL)
                } catch let error as NSError {
                    print("Error: \(error)")
                }
                
                do {
                    try fileManager.removeItemAtURL(signalRTempURL)
                } catch let error as NSError {
                    print("Error: \(error)")
                }
                
                do {
                    try fileManager.removeItemAtURL(jsTempURL)
                } catch let error as NSError {
                    print("Error: \(error)")
                }
                
                do {
                    try fileManager.copyItemAtURL(jqueryURL, toURL: jqueryTempURL)
                } catch let error as NSError {
                    print("Error: \(error)")
                }
                
                do {
                    try fileManager.copyItemAtURL(signalRURL, toURL: signalRTempURL)
                } catch let error as NSError {
                    print("Error: \(error)")
                }
                
                do {
                    try fileManager.copyItemAtURL(jsURL, toURL: jsTempURL)
                } catch let error as NSError {
                    print("Error: \(error)")
                }

**Comment by adamhartford** [comment]
OK, thanks. You're right. Fixing now.

**Comment by adamhartford** [comment]
The code has been updated and SwiftR v0.8.0 released (also published to CocoaPods). Let me know how it works out for you.

**Comment by adamhartford** [comment]
Closing as everything looks good on iOS 9, OS X 10.11 with Swift 2.
