### ISSUE TITLE
Support for ASP.NET Core SignalR

### ISSUE THREAD

**Issue by adincebic** [adamhartford/SwiftR#102]
Is there any hope that this client will get updated so it can work with ASP.NET Core SignalR?

**Comment by adamhartford** [comment]
Yes, definitely! I'll be looking at that in the next few days.

**Comment by JamesBaxter** [comment]
Just looking into using SwiftR with SignalR, it would be really cool to be able write my server side stuff on the Mac too using .net Core

**Comment by relax94** [comment]
Any news in support .net core ?

**Comment by crash481** [comment]
ping

**Comment by CR34L** [comment]
ping
