### ISSUE TITLE
SignalR Connection remains lingering

### ISSUE THREAD

**Issue by nadinasovaiala** [adamhartford/SwiftR#12]
Hello, I noticed that the connections remain in memory after disconnecting, so I was wondering how does that affect performance and is there an easy way to delete the unused SignalR (connection) objects? Thanks!

**Comment by adamhartford** [comment]
They remain in memory so you can reconnect and resume as normal. Are you suggesting something like a `destroy` function that disconnects and removes the connection object, handlers, etc.?

Something like that might be reasonable. Are you aware of any similar functionality in the official/other SignalR clients?

**Comment by nadinasovaiala** [comment]
Yes, a destroy method. I don't know any similar functionality, I just noticed that the number of connections is increasing every time I move from a screen (and I close the connection) and back to the screen (and I start the connection).

**Comment by adamhartford** [comment]
Could you use one connection globally in the application, then stop/start it as needed?

**Comment by nadinasovaiala** [comment]
Yeah, it did the trick. Thanks!
