### ISSUE TITLE
startAll in SignalR.swift mistakenly calls connection.stop

### ISSUE THREAD

**Issue by top2tech** [adamhartford/SwiftR#14]
public class func startAll() {
        checkConnections()
        for connection in connections {
            connection.stop()
        }
    }

Should it call connection.start() ?

**Comment by adamhartford** [comment]
Indeed it should! I'll commit this along with (I hope) something to address issue #13 as well.

**Comment by adamhartford** [comment]
Fixed in commit 8e3a34d223398688c327f222efccdcaa809f7c3d. Thanks again.
