### ISSUE TITLE
exception in shouldHandleRequest

### ISSUE THREAD

**Issue by rsdev-darshan** [adamhartford/SwiftR#17]
getting error ->

fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}: file /Library/Caches/com.apple.xbs/Sources/swiftlang_PONDEROSA/swiftlang_PONDEROSA-700.1.101.6/src/swift/stdlib/public/core/ErrorType.swift, line 50

in SwiftR.swift file

func shouldHandleRequest(request: NSURLRequest) -> Bool {
if request.URL!.absoluteString.hasPrefix("swiftr://") {
let id = (request.URL!.absoluteString as NSString).substringFromIndex(9)
let msg = webView.stringByEvaluatingJavaScriptFromString("readMessage(\(id))")!
let data = msg.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!
let json: AnyObject = try! NSJSONSerialization.JSONObjectWithData(data, options: [])    <-- on this line
processMessage(json)
return false
}
return true
}

**Comment by adamhartford** [comment]
Can you debug and tell me what the value of `msg` is at that point?

Also, what were you doing before this error -- invoking a server method? If so, what does the server method look like and what does it return?

**Comment by rsdev-darshan** [comment]
i am getting blank in msg..

**Comment by rsdev-darshan** [comment]
it was working fine, but it stopped working suddenly... after i updated the pods

**Comment by adamhartford** [comment]
What does your Podfile look like? Does this happen immediately or only after invoking a server method, or something else?

**Comment by rsdev-darshan** [comment]
immediately on calling connect method...

**Comment by rsdev-darshan** [comment]
And actually its fixed now.. 
I rolled back to swift1.2 and again installed swift2 pod.. and it started working.
