### ISSUE TITLE
Converting existing Javascript SignalR to SwiftR

### ISSUE THREAD

**Issue by abinop** [adamhartford/SwiftR#2]
I have a JS implementation of SignalR that goes like this
```
hub = $.connection.thisHub;
$.connection.hub.start().done(function () {
  hub.server.register(true);
});
```
and I am having trouble converting it to the SignalR equivalent.
I have tried
```
SwiftR.connect(url) { (connection) in
      let complexHub = connection.createHubProxy("thisHub")
      complexHub.on("done") { (response) in

  }
}
```

with no success. Any ideas?

**Comment by adamhartford** [comment]
Is your `url` correct? It should be pointing to the root of your site, not to /signalr. Also, what should happen when you invoke `register` on the server? I don't see an event handler in your JS code. You'll want to register that event handler in your Swift code. So, I'd expect to see something like:

``` javascript
// In your JS example, where register eventually calls doSomething
hub.doSomething = function(foo) { ... }
```

and 

```swift
// In your Swift example
complexHub.on("doSomething") { response in ... }
```

**Comment by ArranM** [comment]
Hi, I've managed to get the simulator to transmit to a my .net hub running my Pi via mono. I have issues returning the signalr info but I think thats just me. My issue is trying to get the demo app running on my iOS device. When I build to my device I get the following message. 

dyld: Library not loaded: @rpath/SwiftR.framework/SwiftR
  Referenced from: /private/var/mobile/Containers/Bundle/Application/CDCF0883-AC5E-45BB-9C75-C91FED15350F/SwiftR iOS Demo.app/SwiftR iOS Demo
  Reason: image not found

I'm a noob, and I just wonder if the project build setting was missing something?

This is an amazing bit of code. Thanks in advance for sharing.

**Comment by ArranM** [comment]
Hi, 

Seems to run OK on the simulator to my live .net signalr hub, however when running from my iPhone and selecting complex (hub) I get the following error when hitting 

complexHub.invoke("sendPin", arguments: [message])

fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) 
![screen shot 2015-06-03 at 19 45 04](https://cloud.githubusercontent.com/assets/946806/7968486/195a98ca-0a29-11e5-9bf9-6b0b714b0aa6.png)

Any suggestion? Only changes have been adding where to URL and my Hub names.

Hopefully it's me being dumb as normal. 

Thanks for sharing this SwiftR.

**Comment by adamhartford** [comment]
Hi, there was a bug where I was loading resources from the wrong location (still works in simulator, not on device). 

It's fixed in the most recent commit, though not yet ready for CocoaPods or Carthage. I've verified that it does work on a device. Get the recent changes and give that a shot.

**Comment by ArranM** [comment]
Hi, Fantastic :-)

I'm now running on the device and on the simulator. Sending from the IOS to the .net hub and seeing the update on the web browser screen work out of the box :-). Only issue I seem to have is receiving from the web browser back to the ios device/simulator. All other browser which are connected to the hub update in sync. So I know they are sending a receiving correctly. 

I'll see if there is a Fiddler app for the Mac and check what traffic I am returning.

Thanks once again for share and updating the code. 

Arran

**Comment by adamhartford** [comment]
Fiddler for Mac exists, but is kind of rough. I'd recommend [Charles](http://www.charlesproxy.com).  

v0.4.0 should work round trip unless you've encountered a bug I haven't seen. I'd probably have to see more code to help out.

**Comment by ArranM** [comment]
This is a the version of the ViewController I have, basically cut down version of the sample. (Still learning), Trying the toggle a UISwitch Off/On , Seems happy to send from the iOS to the hub and the web page to reacts (checkbox), however from the webpage/hub back to iOS it does not seem to trigger the println(m). 

Any help would be very much welcomed. :-)

class ViewController: UIViewController {
    
    var switchHub: Hub!
    
    var persistentConnection: SignalR!
    
    @IBOutlet weak var MySwitch: UISwitch!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        // Hubs...
        SwiftR.connect("http://myurl.com:1234") { [weak self] (connection) in
            
            self?.switchHub = connection.createHubProxy("switchHub")
            
            self?.switchHub.on("sendPin") { args in
                let m: AnyObject = args!["0"] as AnyObject!
                println(m)
            }
        }
        
        // Persistent connection..
        persistentConnection = SwiftR.connect("http://myurl.com:1234", connectionType: .Persistent) { (connection) in
            connection.received = { (data) in
                println(data!)
            }
        }
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    @IBAction func MySwitchChange(sender: UISwitch) {
        
        var position = sender.on;
        
        var state = [
            "Pin": 17,
            "Position" : position
        ]
        
        switchHub.invoke("sendPin", arguments: [state])
    }

    @IBAction func sendData(sender: AnyObject?) {
        persistentConnection.send("Persistent Connection Test")
    }
}

/*------------ c# code part--------*/

public class State
    {
        public int Pin { get; set; }
        public bool Position { get; set; }
    }

    public class SwitchHub : Hub<IClient>
    {

        public void SendPin(State state)
        {
            Business.GpioState.Record(state);
            Business.GpioState.SetState(state);

            Clients.All.BroadcastMessage(state);
        }

        public override Task OnConnected()
        {
            Clients.Caller.BroadcastMessageInit(Business.GpioState.Retrieve());

            return base.OnConnected();
        }

        public override Task OnReconnected()
        {
            return base.OnConnected();
        }
    }

**Comment by adamhartford** [comment]
I just tried this, and signaling an iOS function via a web page worked. Here's the JavaScript I used on my page:

```javascript
$(function() {
  var connection = $.hubConnection();
  var simpleHub = connection.createHubProxy('simpleHub');
  simpleHub.on('notifySimple', function(message, detail) {
      alert(message + ': ' + detail);
  });
  connection.start(function() {
    $('a').click(function() {
      simpleHub.invoke('sendSimple', 'foo', 'bar');
    }); 
  });
});
```

Maybe your app lost the SignalR connection? I have to update SwiftR to handle servers going down and make sure it reconnects properly after disconnecting. I haven't tested that part much yet, so that's next. In the mean time, have you tried quitting the app entirely and relaunching to get a new connection?

Have you verified that your server method is called when you trigger an action on your web page (breakpoint in SendPin)? You could use two browsers at first to make sure your SignalR code is working before trying to integrate the iOS app.

If this doesn't help, post the client code you're using with SignalR in your web app.

**Comment by ArranM** [comment]
Hi, Sorry about the delay in responding. (Holidays)

Client code 

$(function () {

    var switchHub = $.connection.switchHub;

    var toggleAll = function (position) {
        var dataList = $('input[name="switchcheckbox"]').map(function () {
            return { Pin: $(this).data("switch"), Position: position };
        }).get();

        return dataList;
    },
    updateSwitch = function (data) {

        $('[data-switch="' + data.Pin + '"]').prop('checked', data.Position);
    },
    updateFeature = function (data) {
        if (data != null) {
            $('[data-switch="0"]').prop('checked', data.Position);
        }
    };

    switchHub.client.broadcastMessage = function (data) {

        updateSwitch(data);
    };

    switchHub.client.broadcastMessageInit = function (data) {

        if (data != null) {
            for (var i = 0; i < data.length; i++) {
                updateSwitch(data[i]);
            }
        }
    };

    switchHub.client.broadcastFeature = function (data) {

        if (data != null) {
            var data2 = toggleAll(data.Position);
            if (data2 != null) {
                for (var i = 0; i < data2.length; i++) {
                    updateSwitch(data2[i]);
                }
            }

            updateFeature(data);
        }

    };

    $.connection.hub.start().done(function () {

        $('[data-action="connectionState"]').html("connected id = " + $.connection.hub.id);

        $('input[name="switchallcheckbox"]').change(function () {

            var data = toggleAll(this.checked),
                delay = 0,
                positon = this.checked,
                direction = 1,
                options = { Feature: "allon", Position: positon, Delay: delay, Direction: direction };

            switchHub.server.sendFeature(options);

            //TODO : Remove from JS , move to feature
            if (data != null) {
                switchHub.server.sendPinAll(data);
            }
        }),

        $('input[name="switchcheckbox"]').change(function () {
            var pin = $(this).data('switch'),
                position = this.checked,
                state = { Pin: pin, Position: position };

            if (this.checked) {
                switchHub.server.sendPin(state);
            } else {
                switchHub.server.sendPin(state);
            }
        });

    }).fail(function () { $('[data-action="connectionState"]').html('Could not connect'); });
});

--------------------------

Html 

 <p>Connection state : <span data-action="connectionState">Off line</span></p>

    <div class="iphone-toggle-buttons">
        <p>toggle all : </p>
        <label for="checkbox-0">
            <input type="checkbox" name="switchallcheckbox" id="checkbox-0" data-switch="0" /><span>checkbox 0</span>
        </label>
    </div>

    <hr />

    <div class="iphone-toggle-buttons">
        <label for="checkbox-4">
            <input type="checkbox" name="switchcheckbox" id="checkbox-4" data-switch="4" /><span>checkbox 4</span>
        </label>
    </div>

    <div class="iphone-toggle-buttons">
        <label for="checkbox-5">
            <input type="checkbox" name="switchcheckbox" id="checkbox-5" data-switch="5" /><span>checkbox 5</span>
        </label>
    </div>

------------------

response from 'Charles', from the web pages 

data	{"H":"switchhub","M":"SendPin","A":[{"Pin":4,"Position":false}],"I":15}

all seem to work fine with browser to browser actions.  I was hoping the following was my issue. 

self?.switchHub.on("SendPin") { args in
                let m: AnyObject = args!["0"] as AnyObject!
                println(m)
            }

**Comment by adamhartford** [comment]
Yeah, looks like you want:

```swift
self?.switchHub.on("broadcastMessage")
```
 instead of

```swift
self?.switchHub.on("sendPin")
```

**Comment by ArranM** [comment]
Wow! FacePalm! Why did I not see that. Brilliant. It's working a treat. Thanks for helping.

**Comment by adamhartford** [comment]
Great! I missed that in your original reply too :)
