### ISSUE TITLE
crash at SwiftR.swift line 354

### ISSUE THREAD

**Issue by top2tech** [adamhartford/SwiftR#20]
I hit a few crashes in my app using SwiftR today.
When the crash happened, I was not sending/receiving any messages, I was just playing around by taking pictures with Camera and displaying pictures in the app.

It crashed at the same place in SwiftR.swift line 354.
I was using version 0.8.1 when the crash happened, 
then I used version 0.8.3,then it crashed again, but this time Crashlytics did not catch the crash, so I'm not 100% sure.

Below is the stack trace caught by Crashlytics:

Thread : Crashed: com.apple.main-thread
0  SwiftR                         0x10252c184 SignalR.(userContentController(SignalR) -> (WKUserContentController, didReceiveScriptMessage : WKScriptMessage) -> ()).(closure #1) (SwiftR.swift:354)
1  WebKit                         0x188cac148 std::__1::__function::__func<-[WKWebView evaluateJavaScript:completionHandler:]::$_0, std::__1::allocator<-[WKWebView evaluateJavaScript:completionHandler:]::$_0>, void (WebKit::WebSerializedScriptValue*, WebKit::CallbackBase::Error)>::operator()(WebKit::WebSerializedScriptValue*&&, WebKit::CallbackBase::Error&&) + 392
2  WebKit                         0x188d66378 WebKit::GenericCallback<WebKit::WebSerializedScriptValue*>::invalidate(WebKit::CallbackBase::Error) + 60
3  WebKit                         0x188cbd418 void WebKit::invalidateCallbackMap<WTF::RefPtr<WebKit::CallbackBase> >(WTF::HashMap<unsigned long long, WTF::RefPtr<WebKit::CallbackBase>, WTF::IntHash<unsigned long long>, WTF::HashTraits<unsigned long long>, WTF::HashTraits<WTF::RefPtr<WebKit::CallbackBase> > >&, WebKit::CallbackBase::Error) + 224
4  WebKit                         0x188d55a74 WebKit::WebPageProxy::resetState(WebKit::WebPageProxy::ResetStateReason) + 460
5  WebKit                         0x188d58468 WebKit::WebPageProxy::resetStateAfterProcessExited() + 192
6  WebKit                         0x188d5e5a4 WebKit::WebPageProxy::processDidCrash() + 44
7  WebKit                         0x188d94fc0 WebKit::WebProcessProxy::didClose(IPC::Connection*) + 264
8  JavaScriptCore                 0x18509eabc WTF::RunLoop::performWork() + 444
9  JavaScriptCore                 0x18509f0f4 WTF::RunLoop::performWork(void*) + 40
10 CoreFoundation                 0x183748240 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
11 CoreFoundation                 0x1837474e4 __CFRunLoopDoSources0 + 264
12 CoreFoundation                 0x183745594 __CFRunLoopRun + 712
13 CoreFoundation                 0x1836712d4 CFRunLoopRunSpecific + 396
14 GraphicsServices               0x18ce876fc GSEventRunModal + 168
15 UIKit                          0x188236fac UIApplicationMain + 1488

**Comment by adamhartford** [comment]
I don't know what to make of that line number, but I rewrote to the function to avoid crashing. Are you able to try to reproduce with this change?

**Comment by top2tech** [comment]
Thanks a lot for the quick response! I will try it today and see how it goes.

**Comment by top2tech** [comment]
I've run it for 2 days, no crash so far. so looks like the fix works well. thanks a lot!
