### ISSUE TITLE
Connecting Users to Group

### ISSUE THREAD

**Issue by NuelNikhil** [adamhartford/SwiftR#31]
How do I connect a user to a Group? I didn't find a Documentation for it. is there any code available to do so???

**Comment by adamhartford** [comment]
I don't think there's anything unique to groups on the client side. Groups should be managed on the server. See: http://www.asp.net/signalr/overview/guide-to-the-api/working-with-groups

**Comment by NuelNikhil** [comment]
Yes... but I think we need to use script to call a function that connects a user to a group. if I need to join a room  we have this method in the server
```
public Task JoinRoom(string roomName)
    {
        return Groups.Add(Context.ConnectionId, roomName);
    }
```
and to call this we need to make a call from front-end like this in Angularjs

```
$scope.EnterRoom = function () {


            chatHubProxy.server.joinroom(grpid);
        };
```

So Can I make any function call like this using SWIFTR ? or any other way in iOS is required?   Correct me if I have any wrong guesses on anything...!

**Comment by adamhartford** [comment]
You should just invoke that like any other server method:

```swift
// SwiftR
chatHub.invoke("joinRoom", arguments: [groupID])
```
