### ISSUE TITLE
Hub.on handler is never called.

### ISSUE THREAD

**Issue by cliapis** [adamhartford/SwiftR#32]
Hello, in my implementation the event names that I need to attach some code are dynamic. This means that I don't now the name of the event before I call the invoke method.

Calling the Hub.on method right before the invoke doesn't seem to be working. The only way to make it work is to call the "Hub.on" methods right after the creation of the hub and before the connection is open.

Any ideas on how to resolve the issue?

**Comment by adamhartford** [comment]
Could you share some code?

**Comment by cliapis** [comment]
Hi, I figured out a way to make it work. It seems that adding a dummy event handler

connection = SwiftR.connect(ConfigurationManager.sharedInstance.configuration.signalRURL) { [unowned self] (connection) in
            
            self.hub = connection.createHubProxy("sportsbookhub")
            self.hub?.on("dummyEvent", callback: { (_) in })
}

Then just before I call the invoke method I perform the "real" handler and it works
self.hub?.on(subscription.pushEvent, callback: { (object) in
...
})

I seems that some initialization is missing. 
I also noticed that if you add a handler on a event twice, event if your swift code uses the event name as a key to you handlers dictionary, you do perform the javascript eval and you end up with 2 events in the javascript context but a single handler in the native context.

**Comment by adamhartford** [comment]
That's good. OK, well I can reproduce both issues you describe. I'll look into them.

**Comment by cliapis** [comment]
Good job by the way ;)

**Comment by adamhartford** [comment]
Thanks :) In this SO question, David Fowler points out that you must have at least one callback defined before starting the connection if you want add others later: http://stackoverflow.com/questions/13497390/signalr-1-0-0-alpha2-hubs-can-you-add-client-functions-after-connection-has

So, it looks like your current approach is correct. Also, I have changes ready to support multiple handlers per event in Swift, which I'll commit tonight.

**Comment by adamhartford** [comment]
Should be all set now. Final answers are:

1. You must add at least one handler before connecting if you want to add others after connecting. Use a dummy handler (like you've done) if you don't have any real handlers to define before connecting.

2. Version 0.10.0 now supports multiple handlers.

Thanks.
