### ISSUE TITLE
Can't handle response

### ISSUE THREAD

**Issue by JimmyYezeguelian** [adamhartford/SwiftR#34]
Hi, 

I'm trying to connect to my server and i can't retrieve the response. I've used Charles on my Mac to see the server response. I can connect to the server, but can't handle response.

I use 
`connection.received = { data in print("data: \(data)") }` but noting is displayed on Xcode debug console.

Thank you by advance

**Comment by adamhartford** [comment]
Could you share more code? It looks like you're trying to use a persistent connection, not a hub?

**Comment by JimmyYezeguelian** [comment]
`func initSignalR(){

        // Connection
        myConnection = SwiftR.connect("myserver", connectionType: .Persistent) { connection in
            
            // Send query
            connection.queryString = ["Authorization": self.token]
            
            // Hub connection
            self.connectionHub = connection.createHubProxy("connectionHub")
            self.newfeedPosts = connection.createHubProxy("newsfeedHub")
            
            // Listener de connexion
            self.connectionHub.on("publishOnline") { args in
                let m: String = args![0] as! String
                if m == "" {
                    print("[]")
                }
                print("publishOnline: \(m)")
            }
            
            // Listener de like sur les posts
            self.newfeedPosts.on("publishpostlike") { args in
                let m: String = args![0] as! String
                if m == "" {
                    print("[]")
                }
                print("publishpostlike: \(m)")
            }
            
            // Test
            self.connectionHub.invoke("ping", arguments: []) { (result, error) in
                if let e = error {
                    print("Error message: \(e)")
                } else {
                    print("Success!")
                    if let r = result {
                        print("Result: \(r)")
                    }
                }
            }
            
            // Event handler
            connection.starting = { print("starting") }
            connection.connected = { print("connected: \(connection.connectionID!)") }
            connection.connectionSlow = { print("connectionSlow") }
            connection.reconnecting = { print("reconnecting") }
            connection.reconnected = { print("reconnected") }
            connection.disconnected = { print("disconnected") }
            connection.received = { data in print("data: \(data)") }
            connection.error = { error in print("error: \(error)") }
        }!
    
        // Start connection
        SwiftR.startAll()
    }
`
Ofc yes, i'm using persistent connection.

**Comment by adamhartford** [comment]
You're defining a persistent connection, but then trying to use hubs. Also remember that you can't invoke a server method until the connection has been made. Your code for a persistent connection should look something like this:

```swift
myConnection = SwiftR.connect("myserver", connectionType: .Persistent) { [weak self] connection in
    // Send query
    connection.queryString = ["Authorization": self.token]

    // Event handler
    connection.connected = { 
        print("connected: \(connection.connectionID!)")

        // Now that you're connected, you can send data...
        self?.sendData()
    }

    connection.received = { data in print("data: \(data)") }
}

// You'd probably call this elsewhere in your app.
func sendData() {
    myConnection.send("some data")
}
```

For hubs, it would look something like this...

```swift
myConnection = SwiftR.connect("myserver") { [weak self] connection in
    // Send query
    connection.queryString = ["Authorization": self.token]

    // Hub connection
    self.connectionHub = connection.createHubProxy("connectionHub")
    self.newfeedPosts = connection.createHubProxy("newsfeedHub")

    // Listener de connexion
    self.connectionHub.on("publishOnline") { args in
        let m: String = args![0] as! String
        if m == "" {
            print("[]")
        }
        print("publishOnline: \(m)")
    }

    // Listener de like sur les posts
    self.newfeedPosts.on("publishpostlike") { args in
        let m: String = args![0] as! String
        if m == "" {
            print("[]")
        }
        print("publishpostlike: \(m)")
    }

    // Event handler
    connection.starting = { print("starting") }
    connection.connected = { 
        print("connected: \(connection.connectionID!)") 

        // Now that you're connected, you can invoke server methods...
        self?.invokeServer()
    }

    connection.connectionSlow = { print("connectionSlow") }
    connection.reconnecting = { print("reconnecting") }
    connection.reconnected = { print("reconnected") }
    connection.disconnected = { print("disconnected") }
    connection.received = { data in print("data: \(data)") }
    connection.error = { error in print("error: \(error)") }
}

func invokeServer() {
    self.connectionHub.invoke("ping", arguments: []) { (result, error) in
        if let e = error {
            print("Error message: \(e)")
        } else {
            print("Success!")
            if let r = result {
                print("Result: \(r)")
            }
        }
    }
}
```

No need to call `SwiftR.startAll()` since connection is started automatically. If I'm misunderstanding something, could you share some server code too?

**Comment by JimmyYezeguelian** [comment]
I'll try this on monday and i tell you what happened.

Thank you for this clear and precise answer

**Comment by JimmyYezeguelian** [comment]
I'm back ! And it works fine ! I now can handle server's responses.
Thank you a lot !

**Comment by adamhartford** [comment]
Glad to hear it! You're welcome.
