### ISSUE TITLE
Change user-agent

### ISSUE THREAD

**Issue by JimmyYezeguelian** [adamhartford/SwiftR#36]
Hi, 

How can i change the user agent of the SignalR connection ?
Thank you by advance

**Comment by adamhartford** [comment]
You can't at the moment. I will add support for that very soon.

**Comment by JimmyYezeguelian** [comment]
OK no problem. When do you think it will be possible ?

**Comment by adamhartford** [comment]
If you need to do this fast, you can use this line of code when your app launches:

```swift
NSUserDefaults.standardUserDefaults().registerDefaults(["UserAgent": "My User Agent"])
```

That'll change your user agent globally. WKWebView on iOS 9 allows you to change it individually I believe, so I'll add that support in SwiftR. But if you're using anything other than WKWebView on iOS 9, you'll need to use the line above anyway.

**Comment by JimmyYezeguelian** [comment]
Oh perfect ! Thank you a lot !!
