### ISSUE TITLE
Expected Declaration

### ISSUE THREAD

**Issue by NuelNikhil** [adamhartford/SwiftR#37]
Hello @adamhartford  again it's me... it's been a while I used SwiftR because I was working with some other stuffs. Now I was trying to make the Hub global by creating a class. When I tried to Add SwiftR I am getting an error saying expected declaration . Please check the Image..
![errorswiftr](https://cloud.githubusercontent.com/assets/7767550/14492364/59254c64-019c-11e6-9510-1036e5f2c7b0.jpeg)

But able to get it work on  my pervious screens... what's happening here ???

**Comment by adamhartford** [comment]
I don't see the image here, but it sounds like your open/close curly braces are not matching. Check to make sure you haven't added and extra closing brace by accident.

**Comment by NuelNikhil** [comment]
I was not able to call SwiftR directly inside a class. But it's getting called inside any function. currently I am looking to create a global hub so that I could Call it in different files. is it possible to crate a global hub ?  a function that returns a **HUB**  ?

**Comment by adamhartford** [comment]
OK, that makes sense. You should just create your hub as normal in any class, then assign it as a property on some global object or your app delegate, etc.

```swift
SwiftR.connect(...) { connection in
    // Assign your hub somewhere such that you'll have access to it anywhere.
    appDelegate.globalHub = connection.createHubProxy("someHub")
}
```

**Comment by NuelNikhil** [comment]
Ohhhh ...  I forget the appDelegate... :)  let me try and will let you know the result...

**Comment by NuelNikhil** [comment]
All set...
