### ISSUE TITLE
Getting Error When Receiving A Message

### ISSUE THREAD

**Issue by charbelhass** [adamhartford/SwiftR#38]
Hello

When I receive a message, i get the following

2016-04-17 18:28:02.346 twicie[4724:1488530] Connection Error: {
    column = 4521;
    errorMessage = "WebSocket closed.";
    line = 8;
    source =     {
    };
    sourceURL = "file:///var/containers/Bundle/Application/58436F8E-A7E3-442C-81E6-944631644DBD/twicie.app/jquery.signalr-2.1.1.min.js";
    transport = webSockets;
}

Any Suggestions??

**Comment by adamhartford** [comment]
Could you share some more code? Other questions:

1. Does it work with a transport other than web sockets? Like server sent events?
2. Can you provide more server details (IIS, Application Request Routing, etc.?)?

**Comment by charbelhass** [comment]
Hello,
Hope you are doing well.

It worked man the issue was that I am trying to use SwiftR with objective C,
I was not able to access Class Hub until I added Hub : NSObject, this was the issue
Now i create a SwiftRManager in swift and I am using it in my objective C project
Thanks

**Comment by adamhartford** [comment]
Ah, that's good to know actually. Thanks!
