### ISSUE TITLE
use more performant WKWebview

### ISSUE THREAD

**Issue by top2tech** [adamhartford/SwiftR#4]
It's a clever idea to build a SignalR client for ios, by wrapping the javascript client. 
In the meantime, it's subject to the performance issue of UIWebView. 
Would you consider using the more performant WKWebView? as discussed here: http://developer.telerik.com/featured/why-ios-8s-wkwebview-is-a-big-deal-for-hybrid-development/

By the way, thanks for the great work!

**Comment by top2tech** [comment]
just saw this releas note: https://github.com/adamhartford/SwiftR/releases/tag/v0.4.0
So there are some issues using WKWebView?

**Comment by adamhartford** [comment]
Yeah, a lot of issues with WKWebView, unfortunately. Most important, I need NSURLProtocol and NSHTTPCookieStorage. I also had request origin issues when running on the device, and problems with Web Inspector with WKWebView on the device. I don't think WKWebView is meant for this kind of thing right now.

This answer summarizes the problem pretty well:
http://stackoverflow.com/questions/24464397/how-can-i-retrieve-a-file-using-wkwebview/24982211#24982211

I wish I could use it though. It'd be nice to have one API for Mac and iOS, and the JavaScript support is much nicer. But, running out of process with no NSURLProtocol is a deal breaker for now.

**Comment by top2tech** [comment]
Thanks for the explanation.
I'm not sure if it can work, but what about using other JS runtime, e.g. JavaScriptCore ? 
It won't work because jquery needs browser?

**Comment by adamhartford** [comment]
Right, XMLHttpRequest is implemented by the browser and isn't part of JavaScript, so it won't be in JavaScriptCore.

I can think of ways to make it work with WKWebView, but you'll be limited to the query string as the only way to send information to the server. No headers/cookies.

Well, you could set custom headers when using non-websocket transports, but cookies would still be an issue. You'd have to set them manually, which would make Forms authentication extra work.

**Comment by top2tech** [comment]
I see. I need custom header for bearer token authentication, and I need websocket for responsiveness. So looks like UIWebView is the only choice. and it won't be too bad regarding UIWebView, right? as probably there is no heave lifting for the javascript, they just send and receive some messages from the wire.

By the way, I'm able to run your sample against a SignalR server, runs beautifully! The memory footprint for the sample is about 20MB, not bad with UIWebView. My next step is to try groups.

**Comment by adamhartford** [comment]
Cool! I think I'll probably revisit WKWebView. It can at least be available as an opt-in feature. If you're OK with some extra setup and aware of the limitations, it could probably be OK for a number of use cases.

**Comment by top2tech** [comment]
Thanks. The ideal combination would be: Custom headers+WebSocket+WKWebView. It's nice to have when you have time.

**Comment by top2tech** [comment]
Actually after my testing, I found out SignalR only supports bearer token in the query string. and bearer token in the header is not reliable(it's not SwiftR's issue, as I can see the correct header in the captured traffic).

So the ideal combination is : queryString+WebSocket+WKWebView.
looks like doable?

**Comment by top2tech** [comment]
Correction, the customized header is NOT sent to the server in some cases.
Looks like Browser(i.e. javascript client) does not support custom headers, according to the answer here: http://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api

below is the captured traffic:

### custom header(Authorization) sent in protocol negotiation: 
GET http://192.168.0.123:9000/signalr/negotiate?clientProtocol=1.5&_SwiftR=1&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&_=1436025463932 HTTP/1.1
Host: 192.168.0.123:9000
Authorization: bearer AAEAACWkU5qCgRWay2Y(ommited)
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept-Language: en-us
Accept: text/plain, */*; q=0.01
Connection: keep-alive
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12F69

### Server response 200:
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8
Server: Microsoft-HTTPAPI/2.0
X-Content-Type-Options: nosniff
Date: Sat, 04 Jul 2015 15:57:43 GMT

{"Url":"/signalr","ConnectionToken":"AAEAALUqJ4(ommited)","ConnectionId":"8466a85e-109a-47ee-8afe-293316e4a9d9","KeepAliveTimeout":20.0,"DisconnectTimeout":30.0,"ConnectionTimeout":110.0,"TryWebSockets":true,"ProtocolVersion":"1.5","TransportConnectTimeout":5.0,"LongPollDelay":0.0}


### custom header(Authorization) NOT sent in trying to connect via WebSocket
GET http://192.168.0.123:9000/signalr/connect?transport=webSockets&clientProtocol=1.5&_SwiftR=1&connectionToken=AAEAALUqJ4(ommited)&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&tid=7 HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: 192.168.0.123:9000
Origin: file://
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: ufIMqNxARJD/7ShttVqabQ==
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: x-webkit-deflate-frame
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12F69

### server response 401:
HTTP/1.1 401 Unauthorized
Content-Length: 0
Server: Microsoft-HTTPAPI/2.0
Access-Control-Allow-Origin: file://
Access-Control-Allow-Credentials: true
X-Content-Type-Options: nosniff
Date: Sat, 04 Jul 2015 15:57:43 GMT

**Comment by adamhartford** [comment]
Hm, you're right. I knew the JavaScript WebSockets API doesn't support custom headers, but thought I could work around that limitation with NSURLProtocol. I guess this means UIWebView doesn't use the standard iOS URL loading system for WebSockets, so there's nothing to intercept on which I can set headers.

This might be one less reason to stick with UIWebView. Custom headers on non-websocket transports should be OK with WKWebView. So query string + WebSockets + WKWebView is probably the best case scenario.

**Comment by adamhartford** [comment]
Commit b52558c35bee471401aef92739bf10cc9d94db68 brings back support for WKWebView. I also changed the way you specify custom headers and added the ability to specify the transport.

It turns out the main issue I was having was related to executing JavaScript in a hidden WKWebView. See: http://stackoverflow.com/questions/26514090/wkwebview-does-not-run-javascriptxml-http-request-with-out-adding-a-parent-vie#answer-26575892

At this point, I think the only reason to use UIWebView is if you need cookies from NSHTTPCookieStorage. You won't be able to specify custom headers when using WebSockets, so SwiftR will naturally have the same limitations as the SignalR JavaScript client. I'm OK with that as a consequence of this (I think) pretty simple approach of working with SignalR in Swift.

I haven't updated the README yet, so look at the updated demo app as an example.

**Comment by top2tech** [comment]
Nice! I just tried 0.60, works great with WKWebView!
