### ISSUE TITLE
Error event not called

### ISSUE THREAD

**Issue by ctrl-shift** [adamhartford/SwiftR#40]
After update from 0.9.0 to 0.10.0 connection.error event is not called anymore when error happens.
Javascript seems to be returning `msg` nil in [didReceiveScriptMessage](https://github.com/adamhartford/SwiftR/blob/master/SwiftR/SwiftR.swift#L431) when error is happening.
Possibly related to [multiple event handlers](https://github.com/adamhartford/SwiftR/commit/e1db43e181d37b9e30c96cbc8e058d703ce9ec7c) feature

**Comment by adamhartford** [comment]
Thank you for the report. I can reproduce this too, so I'll look into it.

**Comment by adamhartford** [comment]
This is fixed in the master branch.
