### ISSUE TITLE
Connection State shows "Starting" but not getting connected

### ISSUE THREAD

**Issue by NuelNikhil** [adamhartford/SwiftR#45]
Able to send 4 messages continuously but on sending the 5th message nothing else happens other than printing this message "Starting"

```
 SwiftR.connect("http://url/signalr/")
            {
                connection in
                    let signalrHub = connection.createHubProxy("chatHub")
                print("HUb : \(signalrHub)")
               
                signalrHub.on("recevivemessage")
                    {
                        args in
                            print("Response from Server : \(args)")
                        let message = JSQMessage(senderId: senderId, senderDisplayName: senderDisplayName, date: date, text: text)
                        self.messages += [message]
                        self.finishSendingMessage()
                    }
                
                connection.connected = {
                     self._userHubId = signalrHub.connection.connectionID!
                     print("Current Signalr id : \(self._userHubId)")
}
 connection.disconnected = {
                    
                    print("Disconnected")
                    
                    // Try again after 5 seconds
                    let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(5 * Double(NSEC_PER_SEC)))
                    dispatch_after(delayTime, dispatch_get_main_queue()) {
                        connection.start()
                    }

                }
                
                connection.connectionSlow = {
                    print("Connection slow")
                }
                
                connection.reconnecting = {
                    print("Reconnecting")
                }
                
                connection.reconnected  = {
                    print("Reconnected"
                }
               
                connection.starting = {
                    print("Starting")
                }
```)

I am getting SwiftR.Hub even at the fifth message but nothing more ... Any Idea about the situation?

**Comment by NuelNikhil** [comment]
It's been long and it didn't even work till now... any suggestions ??? :(

**Comment by NuelNikhil** [comment]
@adamhartford  I have been trying to make signalr to connect my server using swiftr , but nothing more happening... I have a button to send message to server. I would like to know whether I am using SwiftR in correct manner.... I use the code above (the issue I have posted) inside button click event... after a few messages( let's say a count of 5) the code doesn't even entering the connected state where I call the server side code. Without getting inside the connected state I won't get a conenctionID(required to pass as a parameter to Server side code). So can you give a sample on how to make SwiftR to call a server side code in situation like chatting ???

**Comment by adamhartford** [comment]
I've published a sample SignalR application called [SwiftRChat](https://github.com/adamhartford/SwiftRChat) to http://swiftr.azurewebsites.net. I've also updated the SwiftR iOS demo application to use this server. If you can reproduce the issue with the demo iOS app and public demo SignalR server, please let me know.

Otherwise, the only way I can help is if you publish your own SignalR server somewhere such that it's publicly available, and provide an example iOS application that demonstrates the problem.

**Comment by NuelNikhil** [comment]
@adamhartford  I tried the sample code it's working... I called your server using my project and it worked too... Thank you for that Sample project... 👍
