### ISSUE TITLE
how do the install?

### ISSUE THREAD

**Issue by mowali** [adamhartford/SwiftR#51]
why is the installation so brief!? I can't run the project. I get a link error: "command error with exit code 1"
The installation step says to create a pod file!? why? I just want to run the project to see the code
anyway, I created a signalR pod which installed a whole project that doesn't build, run or anything!?
Why is the installation step so brief!?
Can you add a couple of lines of what we are trying achieve there? 
since the project doesn't run by itself.
I added more description here: http://stackoverflow.com/questions/37308604/in-xcode-project-i-get-this-linker-command-error-with-exit-code-1

**Comment by vahidamini** [comment]
Is your problem solved?

**Comment by mowali** [comment]
yes just got solved.
