### ISSUE TITLE
Xcode 8 & Carthage - Build Failed

### ISSUE THREAD

**Issue by SamuelFrankSmith** [adamhartford/SwiftR#58]
Carthage is failing with Xcode 8 - beta 6 (and probably earlier betas).

```
The following build commands failed:
    Check dependencies
(1 failure)
warning: no umbrella header found for target 'SwiftR iOS', module map will not be generated
warning: no umbrella header found for target 'SwiftR iOS', module map will not be generated
A shell task (/usr/bin/xcrun xcodebuild 
-project /Users/<redacted_path>/Carthage/Checkouts/SwiftR/SwiftR.xcodeproj 
-scheme SwiftR iOS 
-configuration Release 
-sdk iphoneos 
ONLY_ACTIVE_ARCH=NO 
BITCODE_GENERATION_MODE=bitcode 
CODE_SIGNING_REQUIRED=NO 
CODE_SIGN_IDENTITY= 
CARTHAGE=YES clean build) 
failed with exit code 65:
** CLEAN FAILED **
```

Here is a [potentially-related issue from another project](https://github.com/socketio/socket.io-client-swift/issues/432).

**Comment by SamuelFrankSmith** [comment]
I've corrected the Carthage issue in [my swift3 branch](https://github.com/SamuelFrankSmith/SwiftR/tree/swift3), but I don't feel ultra-confident in its correctness. See my updates to the README.

**Comment by adamhartford** [comment]
Thanks! I'll take a look. I'm still waiting for the dust to settle around Xcode 8 and Swift 3, but it seems like it's probably time to start planning for it.
