### ISSUE TITLE
Compiler errors in Swift 2.3

### ISSUE THREAD

**Issue by cliapis** [adamhartford/SwiftR#61]
Hi I trying to migrate to Swift 2.3 as a first step before 3.0 in order to move to Xcode 8.

But I get some compiler errors regarding optionals unwrapping .

for example in the cleanup() function there is a problem using the jqueryTempURL without '?'.

I am having this issue in both 0.10.0 and .0.11.0 version
`
if let path = jqueryTempURL.path where fileManager.fileExistsAtPath(path) {
    try fileManager.removeItemAtURL(jqueryTempURL)
}
`

So what's the status with the 2.3 and 3.0 versions?

Thanks

**Comment by skerkewitz** [comment]
I run into the same problem. I just forked the project (hopefully) fixed all issues for Swift 2.3.

Have a look here: https://github.com/skerkewitz/SwiftR/tree/swift23

@adamhartford Do you have any interest in Swift 2.3 or do you plan to skip it completely? Should I create a pull request? I assume in the long run everybody will update to Swift 3 eventually.

**Comment by adamhartford** [comment]
I personally don't have an interest in Swift 2.3, but I'm more than happy to accept a pull request for it!

**Comment by adamhartford** [comment]
I just created a `swift23` branch. Would you able to submit a pull request there?

**Comment by skerkewitz** [comment]
Should be no problem. I will have a look tomorrow when I'm back in the office.

**Comment by srinadhK** [comment]
HI, here also getting errors after updated to pods. But i am running app on Xcode 7.3.1

**Comment by adamhartford** [comment]
@srinadhK You need to stay on version 0.11.0 if you still need Swift 2.2 and Xcode 7. Reference that version directly in your Podfile.

**Comment by srinadhK** [comment]
@adamhartford can you please give me a pod file spec. i do it.

**Comment by skerkewitz** [comment]
@adamhartford I had a look at your `swift23` branch. Unfortunatly it branches from your latest commit, including all your Swift 3.0 changes. It would be easier if `swift23` would branch from your `0.11.0` tag.

**Comment by adamhartford** [comment]
@skerkewitz Oh, I had assumed you originally forked from master and would have an easier time that way. I just recreated `swift23` from the `0.11.0` tag.

**Comment by adamhartford** [comment]
There is now a swift 2.3 branch you can reference in your Podfile as follows:

```ruby
pod 'SwiftR', :git => 'https://github.com/adamhartford/SwiftR.git', :branch => 'swift23'
```

Thanks @skerkewitz!
