### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by cliapis** [adamhartford/SwiftR#66]
Hello, I see that your implementation is based on javascript running on a web view. 
The problem is that web views (WK* and UI*) are not available in tvOS .

Do you have any plans on dropping the dependency on web views in the near future?
Are the TVML or TVJS  capable of running your javasctipt code?

I am using your library for our iOS application and we are now investigating the posibility of a tvOS app and the Signal R support is mandatory in our business.

Thank you.

**Comment by adamhartford** [comment]
Sorry, the answer to both is no. For me, wrapping the JavaScript client was the easiest and least risky way to support SignalR in iOS. So, this project will rely on a web view for the foreseeable future.
