### ISSUE TITLE
Disconnection when .on from client.

### ISSUE THREAD

**Issue by nvduc2910** [adamhartford/SwiftR#68]
Hi adamhartford,

First, Thank you for library, I really happy when found the library but I have one problem , I hope you help.

Everything working fine but when I use .on function . I got the error: Error: Optional(["source": Internal Server Error, "message": Error during start request. Stopping the connection.])

That mean

Code working fine:

connection = SwiftR.connect("http://baotn.ddns.net:9999/signalr/hubs") { [weak self] connection in
            self?.chatHub = connection.createHubProxy("shippingEasyHub")

But  I add .on function it disconnection..

connection = SwiftR.connect("http://baotn.ddns.net:9999/signalr/hubs") { [weak self] connection in
            self?.chatHub = connection.createHubProxy("shippingEasyHub")
            
            
            self?.chatHub?.on("broadcastMessage") { args in
                if let name = args?[0] as? String, let message = args?[1] as? String, let text =            self?.chatTextView.text {
                    self?.chatTextView.text = "\(text)\n\n\(name): \(message)"
                }
            }
          
Please help me soon. I really need for help. Thanks very much

**Comment by nvduc2910** [comment]
I have found cause. my OnConnect function have problem. Thank you again

**Comment by adamhartford** [comment]
Glad to hear it.
