### ISSUE TITLE
WebCore::FloatPoint Exception

### ISSUE THREAD

**Issue by SamuelFrankSmith** [adamhartford/SwiftR#69]
`SwiftR.useWKWebView = false` results in an exception in WebCore::FloatPoint::FloatPoint: assembly.
`SwiftR.usWKWebView = true` results has no issues.

Occurs immediately after calling `SwiftR.connect(url) {...}`

- Using the latest from 'master' branch.
- This is a new issue, as it wasn't occurring before Swift 3 release.

Let me know what other information I can provide.

**Comment by adamhartford** [comment]
Can you provide some information about the server you're using (version, URL, etc.)? Since this doesn't happen with the demo project/server, I'm going to guess it's somehow server-related.

**Comment by SamuelFrankSmith** [comment]
I'm fearing it might be server too, just wanted to see if this provoked any "aha" moments.
Server: version 2.2.0
Any way to get a console output of what the SignalR library or SwiftR is up to? Can I leverage Safari at all?

**Comment by adamhartford** [comment]
Yeah, you can open a Safari Web Inspector instances when running in the simulator or on the device. In there, you can debug SwiftR.js and also see console logs from SignalR.

FWIW, the usual culprit is CORS when it works with UIWebView but not WKWebView. First make sure you have CORS enabled.

**Comment by SamuelFrankSmith** [comment]
Looks like the issue was that it SwiftR wasn't connecting from the main thread. UIKit, and its UIWebView, was rather displeased with this scenario. Thanks again for your help.
