### ISSUE TITLE
Having difficulties with SwiftR

### ISSUE THREAD

**Issue by cody1024d** [adamhartford/SwiftR#70]
I'm having difficulty getting SwiftR to function.  I am working on a Swift-port of an application previously written in Objective-C, where we were using Objc-SignalR.  The previous application works, and is able to register for a callback, and receives them correctly.

With SwiftR, I am invoking the correct hub method, and I receive no errors, however, none of my callbacks ever fire.  I have already confirmed that the arguments are the same (although the JSON sent over Objc-SignalR, when I stepped through it, contained the method name, etc. tacked on by Objc-SignalR), and so am utterly confused what else could be happening.

Here is the actual SwiftR interaction code:

```swift
        SwiftR.connect(serverUrl) { connection in
            connection.error = { error in
                print(error)
            }
            connection.connectionFailed = {
                print("connectionFailed")
            }
            let countHub = connection.createHubProxy("CheckIn")
            countHub.on("SubscribeRoomUpdateCallback", callback: self.subscribeCallBack)
            countHub.on("CheckinRoomCountUpdate") { self.roomCountUpdated(args: $0, callBack: callBack) }
            let subscribeRequestJson = subscribeRequest.toJSON()
            countHub.invoke("SubscribeRoomUpdate", arguments: [subscribeRequestJson]) { result in
                print(result)
            }
            self.countHub = countHub
        }
```

**Comment by adamhartford** [comment]
Make sure you're waiting until the connection is made before invoking a hub method. Try this:

```swift
SwiftR.connect(serverUrl) { connection in
    connection.error = { error in
        print(error)
    }
    connection.connectionFailed = {
        print("connectionFailed")
    }
    let countHub = connection.createHubProxy("CheckIn")
    countHub.on("SubscribeRoomUpdateCallback", callback: self.subscribeCallBack)
    countHub.on("CheckinRoomCountUpdate") { self.roomCountUpdated(args: $0, callBack: callBack) }
    self.countHub = countHub

    connection.connected = {
        let subscribeRequestJson = subscribeRequest.toJSON()
        countHub.invoke("SubscribeRoomUpdate", arguments: [subscribeRequestJson]) { result in
            print(result)
        }
    }
}
```

**Comment by cody1024d** [comment]
Ah, I figured once the connection was returned, that it was connected.  That's what happens when you assume!  --I'll try that right now

**Comment by cody1024d** [comment]
That worked!  Closing this.  Thanks for the quick response @adamhartford.

Just as an aside, I feel like it is a big ambiguous, that the connection object within that callback isn't actually connected yet, but is still returned to me to be used.

**Comment by adamhartford** [comment]
You're welcome. I hear ya. I've never been really happy with it myself, but set it up the way I needed it to work  in the beginning and never changed it. Maybe `SwiftR.start` or `SwiftR.create` `SwiftR.initialize` or something like that would be better? I'd happily take some suggestions.

It just needs to complete that callback routine to setup hubs, etc. before actually starting to communicate with SignalR.
