### ISSUE TITLE
Error: Optional(["message": Error during negotiation request.])

### ISSUE THREAD

**Issue by sathyabaman** [adamhartford/SwiftR#75]
Hi iam trying to connect to Hub. But getting the error like this 

```
Starting...
Error: Optional(["message": Error during negotiation request.])
Disconnected.
```

I have posted the full question here in stackoverflow.
http://stackoverflow.com/questions/41162408/signal-r-in-swift

Can you please help me to fix this.

**Comment by adamhartford** [comment]
Does it work with `SwiftR.useWKWebView = false`?

If so, make sure you have CORS enabled on your server. CORS is required for WKWebView to work with SwiftR.

**Comment by tejasverixo** [comment]
Having same issue. Help us to fix this.

**Comment by adamhartford** [comment]
@tejasverixo Please answer same questions RE: wkWebView = false, and whether or not CORS is enabled on your SignalR server.

**Comment by tejasverixo** [comment]
By default SwiftR.useWKWebView = false - It's working fine.
but as per the [example ](https://github.com/adamhartford/SwiftR/blob/swift23/SwiftR%20iOS%20Demo/DemoViewController.swift) if its "True" - It's Not working.  

//As per the "Master" branch update i m getting following error

**//Code** 
 connection = SignalR("http://swiftr.azurewebsites.net")

**//Error**
"Cannot invoke initializer for type 'SignalR' with an argument list of type '(String)'"

**Note:** I did Installation using Pod 

I have posted the full question here in stackoverflow.
http://stackoverflow.com/questions/41221263/signalr-implementation-using-swift-3-0

**Comment by adamhartford** [comment]
@tejasverixo I posted this on SO, but will paste here too:

The pod (swift3), the swift23 branch, and the master branch (API changes) are all different code. You'll need to pick one version of the library and stick with it. If WKWebView = false works, but true doesn't, that means you probably don't have CORS enabled on your SignalR server.

CORS is most likely the culprit here.

**Comment by Podiya** [comment]
hey im having same issue. when i false SwiftR.useWKWebView it, server responding with this error
`message = "Error during start request. Stopping the connection.";
    source = "Internal Server Error";`

**Comment by qazaleh** [comment]
Hi I am trying to use swiftR , i don't know anything about this, I do not chat application. I don't know where should call server method from client and send parameter to server, or call client method from server and send JSON to client.  please help me to fix this, thanks.

**Comment by amralkhayat** [comment]
Hello i am trying to SwiftR with core signal version 2.4 but your library support v2.2, how can i upgrade the version?

**Comment by georgenimber** [comment]
Anyone having the same issue now that UIWebView is not available ?
