### ISSUE TITLE
Cannot initialize connection

### ISSUE THREAD

**Issue by kenakamu** [adamhartford/SwiftR#78]
with Swift 3 and SwiftR 0.12.0 (installed via CocoaPod) i cannot instantiate connection as it claims to require not only String (connectionString) but also type and handler.

**Comment by adamhartford** [comment]
The documentation on the master branch is for v0.13.0, which includes API changes. You'll need to look at the v0.12.0 documentation available at cocoapods.org.

However, I just published v0.13.0 to CocoaPods. If you update, the code you're using will match the README on the master branch.
