### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by s2339956** [adamhartford/SwiftR#79]
Starting...
SignalR Error: Optional(["message": You are using a version of the client that isn't compatible with the server. Client version 1.5, server version 1.4.])

The original swift2.3 swift3 upgrade to the emergence of such a message
Originally swift2.3 normal
Is this what is the problem? ??

**Comment by adamhartford** [comment]
The default assumed SignalR version was changed from 2.2.0 to 2.2.1. Sounds like you need to specify the correct version you're using:

```swift
connection.signalRVersion = .v2_2_0 // Or whatever it is
```
