### ISSUE TITLE
How can I join a room in SwiftR

### ISSUE THREAD

**Issue by mohammadZ74** [adamhartford/SwiftR#86]
I have rooms in my signalR server ... how can I join specific room in swift 3?

**Comment by mohammadZ74** [comment]
can you please answer me? :(

**Comment by mohammadZ74** [comment]
down below is url which I get message for roomname named "testroom"
http://speedapp.ir/test/index/testroom
and this is my url for sending message:
http://speedapp.ir/test/send/testroom

the problem is I cannot even connect to this url: http://speedapp.ir/test/index/testroom but it working correctly on web client and when I try to connect to just 'http://speedapp.ir' I connected Successfully but it's not useful .... this is my code:
connection = SignalR("http://speedapp.ir/test/index/testroom")
        connection.useWKWebView = false

       
        connection.signalRVersion = .v2_2_1
        
        chatHub = Hub("signalRChatHub")

**Comment by CaptainHunter** [comment]
Hello @mohammadZ74! 
Did you manage to initialise SignalR [SignalR("http://speedapp.ir/test/index/testroom")] and Hub [Hub("signalRChatHub")]?

My SignalR entities aren't working. If yours is, do you mind sharing the steps that you took to make it work?
<img width="898" alt="screen shot 2017-04-27 at 1 33 55 am" src="https://cloud.githubusercontent.com/assets/28061999/25448394/db72c7c8-2aea-11e7-8364-58d039d875ee.png">

**Comment by mohammadZ74** [comment]
I think you probably shouldn't initiliaze in static func... @CaptainHunter

**Comment by CaptainHunter** [comment]
I am still getting the same error. Btw, did you get your SwiftR through Cocoapods?
