### ISSUE TITLE
Need support for Swift3.1 , XCode 8.3.1

### ISSUE THREAD

**Issue by ramyasrikontham** [adamhartford/SwiftR#87]
I updated my xcode to xcode 8.3.1 , installed pod 'SwiftR’,‘0.11.0’ and also tried with pod 'SwiftR’ but i remain with syntactical errors. 
Please solve this issue.

**Comment by adamhartford** [comment]
Version 0.11.0 is for Swift 2.2. For Swift 3, use version 0.12.0 or higher.
