### ISSUE TITLE
Cannot initialise SignalR and Hub

### ISSUE THREAD

**Issue by CaptainHunter** [adamhartford/SwiftR#88]
<img width="898" alt="screen shot 2017-04-27 at 1 33 55 am" src="https://cloud.githubusercontent.com/assets/28061999/25447976/a9113c8e-2ae9-11e7-853a-35ff1925a310.png">

I have installed SwiftR (0.12.0) through Cocoapods, and it is not working for me. 
It seems like both the SignalR and Hub entity cannot be initialised.

Please help!!

**Comment by adamhartford** [comment]
The code you're showing is for version 0.13.0. Please update your pod to that version.
