### ISSUE TITLE
How can i disconnect the connection?

### ISSUE THREAD

**Issue by rsdev-darshan** [adamhartford/SwiftR#9]
I dint find a way to disconnect the connection, did i miss something or its not possible?

**Comment by adamhartford** [comment]
It's not possible at the moment. I will add this support. I'll keep this issue open until it's done.

**Comment by rsdev-darshan** [comment]
ohkay... Thanks

**Comment by adamhartford** [comment]
Commit 1bd2784bab7cf60f248ae4f483f2942ea95e4f5f adds this functionality. See the updated iOS demo app for an example of how to use it. I haven't merged this into the swift2 branch yet, and will wait a bit before release via CocoaPods. Let me know how it works out for you.

**Comment by adamhartford** [comment]
Closing now that this functionality is in v0.7.0.
