### ISSUE TITLE
SwiftR + Xcode 9

### ISSUE THREAD

**Issue by dyountmusic** [adamhartford/SwiftR#96]
Seems to be some breaking changes with the way SwiftR is compiling inside of Xcode 9 for the latest version of this master branch?

Anybody else experiencing something similar?

**Comment by jsembdner** [comment]
Have you tried Xcode 9 GM? Working fine for me with cocoapods.

**Comment by dyountmusic** [comment]
Yeah, running Xcode 9 GM. Xcode compiler is telling me that the `SwiftR.connect()` method is missing a parameter of `<#UnsafePointer<sockaddr>!#>` so it looks like it's not actually attempting to call the appropriate method. It almost seems like all references to just `SwiftR.something()` has broken. Another method call in my codebase of `SwiftR.stopAll()` has also broken.

Will post an update if I can get it working.

**Comment by ayman-karram** [comment]
@dyountmusic did you make this run?

**Comment by adamhartford** [comment]
I haven't seen this problem before. Would someone being willing to post an example project that demonstrates the issue?

**Comment by ayman-karram** [comment]
[SignalRSample.zip](https://github.com/adamhartford/SwiftR/files/1475136/SignalRSample.zip)
@adamhartford  check this example

**Comment by adamhartford** [comment]
I see. This example hasn't been updated since the SwiftR API changed. The SwifR.* functions aren't used anymore as of v0.13.0. From the release note:

> You now create a SignalR instance instead of using SwiftR.connect(). This is intended to make the setup code easier to read and understand, and allows the connection setup to be done outside of callback (a common question/complaint).
> 
> If you do not want to update your code for these changes, point your SwiftR Podfile reference to version 0.12.0.

The correct syntax for v0.13.0 and higher is in the README and the demo project.
